version: "3.9"

services:
  db:
    image: postgres:16.1
    env_file:
      .env
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis

  web:
    build: .
    image: movies_rating_web
    depends_on:
      - db
      - redis
    volumes:
      - .:/src
      - static:/static
    env_file:
      - .env

    command: /bin/bash -c "pip install -r requirements.txt && invoke runit"

  client:
    image: node:21.6.2
    volumes:
      - ./client:/src
    command: /bin/bash -c "cd /src/; npm i; npm run dev"
    ports:
      - 3000:3000

  nginx:
    image: nginx:1.25.4
    networks:
      - default
      - nginx-proxy
    volumes:
      - static:/static:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
      - client
    ports:
      - "8000:80"
    environment:
      - VIRTUAL_HOST=diploma.ryzhenko.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=diploma.ryzhenko.com
      - LETSENCRYPT_EMAIL=admin@diploma.ryzhenko.com

networks:
  default:
  nginx-proxy:
    name: nginx-proxy

volumes:
  pgdata:
  static: