version: 2.1

# Define the jobs we want to run for this project
jobs:
  prospector:
    docker:
      - image: playmouse/movies_rating-deploy
    steps:
      - checkout
      - restore_cache:
          key: python-dev-requirements
      - run: pip install -r requirements-dev.txt
      - save_cache:
          key: python-dev-requirements-3.9
          paths:
            - /usr/local/lib/python3.9/site-packages
#      - run: prospector apps -X

  deploy_dev:
    docker:
      - image: playmouse/movies_rating-deploy
    steps:
      - checkout
      - run: pip install boto3 pexpect

      - add_ssh_keys:
          fingerprints:
            - "SHA256:MYPMtB73kkNfZuLq8ryxgO2PgKXmSn2XMzq/FC9VLHU"

      - run: python deploy.py

# Orchestrate our job run sequence
workflows:
  check_and_deploy:
    jobs:
      - prospector
      - deploy_dev:
          requires: ['prospector',]
          filters:
            branches:
              only:
                - main