version: 2.1

# Define the jobs we want to run for this project
jobs:
  prospector:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - restore_cache:
          key: python-dev-requirements
      - run: pip install -r requirements-dev.txt
      - save_cache:
          key: python-dev-requirements-3.9
          paths:
            - /usr/local/lib/python3.9/site-packages
      - run: prospector apps -X

# Orchestrate our job run sequence
workflows:
  check_code:
    jobs:
      - prospector
