# Generated by Django 4.2.10 on 2024-05-04 18:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_person_known_for_titles_alter_personmovie_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='known_for_titles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255, null=True, verbose_name='Known for titles'), default=[], size=None),
            preserve_default=False,
        ),
    ]
