# Generated by Django 4.2.10 on 2024-05-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_alter_rating_movie_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="poster",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Type of title"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="photo",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Type of title"
            ),
        ),
    ]
