# Generated by Django 4.2.10 on 2024-05-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_movie_poster_person_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.CharField(max_length=255, null=True, verbose_name="Poster"),
        ),
        migrations.AlterField(
            model_name="person",
            name="photo",
            field=models.CharField(max_length=255, null=True, verbose_name="Photo"),
        ),
    ]
