# Generated by Django 4.2.10 on 2024-05-10 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_alter_movie_poster_alter_person_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="personmovie",
            name="movie_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
            ),
        ),
        migrations.AlterField(
            model_name="personmovie",
            name="person_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="movies.person"
            ),
        ),
    ]
